vich_uploader:
    db_driver: orm

    mappings:
        thumbnails:
            uri_prefix: /images/thumbnails
            upload_destination: '%kernel.project_dir%/public/images/thumbnails'

        productMedia:
            uri_prefix: /uploads/product
            upload_destination: '%kernel.project_dir%/public/uploads/product'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer


        your_image_mapping:
            uri_prefix: /uploads/category
            upload_destination: '%kernel.project_dir%/public/uploads/category'
            namer: Vich\UploaderBundle\Naming\OrignameNamer




